modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/Ipsis/Woot/issues" #optional
#displayURL="http://example.com/" #optional
credits="McJty, Draco18s, Forge Devs"
authors="Ipsis" #optional

[[mods]] #mandatory
modId="woot" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Woot" #mandatory
description='''
A big, bad, magic, multiblock.
Aparrently you will either love it or hate it.
There is no inbetween.
'''

