modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Ipsis/Woot/issues"

[[mods]]
modId="woot"
version="${file.jarVersion}"
displayName="Woot"
authors="Ipsis"
credits="McJty, Draco18s, Forge Devs"
description='''A big, bad, magic, multiblock for mob drops. Aparrently you will either love it or hate it. There is no inbetween.'''


